import {
  FormCheckbox,
  FormInput,
  FormTextarea,
} from '../../../components/common/FormComponents';
import FormInputWithSuggestions from '../../../components/common/FormInputWithSuggestions';
import {
  fetchSuggestionsByBookISBN,
  fetchSuggestionsByBookTitle,
} from '../../utils/fetchUtils';
import { getInputClass } from '../../utils/formUtils';

const getBookFormFields = ({ formData, handleFieldChange, handleSelectSuggestion }) => [
  {
    component: FormInputWithSuggestions,
    label: 'ISBNs',
    id: 'isbn',
    name: 'isbn',
    value: formData.isbn,
    onChange: handleFieldChange,
    onSelectSuggestion: handleSelectSuggestion,
    validClass: getInputClass(formData.validIsbn, 'isbn'),
    fetchSuggestions: fetchSuggestionsByBookISBN,
    renderItem: (item) => `${item.title} - ${item.authors.join(', ')}`,
    children: <span className='nowrap'>{'[ISBN or TITLE needed]'}</span>,
  },
  {
    component: FormInputWithSuggestions,
    label: 'Title',
    id: 'title',
    name: 'title',
    value: formData.title,
    onChange: handleFieldChange,
    onSelectSuggestion: handleSelectSuggestion,
    validClass: getInputClass(formData.validTitle),
    fetchSuggestions: fetchSuggestionsByBookTitle,
    renderItem: (item) => `${item.title} - ${item.authors.join(', ')}`,
    children: <span className='nowrap'>{'[ISBN or TITLE needed]'}</span>,
  },
  {
    component: FormInput,
    label: 'Author(s):',
    id: 'authors',
    name: 'authors',
    type: 'text',
    value: formData.authors,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'Publisher:',
    id: 'publisher',
    name: 'publisher',
    type: 'text',
    value: formData.publisher,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'Published Date:',
    id: 'publishedDate',
    name: 'publishedDate',
    type: 'date',
    value: formData.publishedDate,
    onChange: handleFieldChange,
  },
  {
    component: FormTextarea,
    label: 'Description:',
    id: 'description',
    name: 'description',
    rows: 5,
    value: formData.description,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'Categories:',
    id: 'categories',
    name: 'categories',
    type: 'text',
    value: formData.categories,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'ThumbnailUrl:',
    id: 'thumbnailUrl',
    name: 'thumbnailUrl',
    type: 'text',
    value: formData.thumbnailUrl,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'imageUrl:',
    id: 'imageUrl',
    name: 'imageUrl',
    type: 'text',
    value: formData.imageUrl,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'Language:',
    id: 'language',
    name: 'language',
    type: 'text',
    value: formData.language,
    onChange: handleFieldChange,
  },
  {
    component: FormCheckbox,
    label: 'On Wishlist:',
    id: 'isOnWishlist',
    name: 'isOnWishlist',
    checked: formData.isOnWishlist,
    onChange: handleFieldChange,
  },
];

export default getBookFormFields;
