import {
  FormCheckbox,
  FormInput,
  FormTextarea,
} from '../../../components/common/FormComponents';
import {
  handleAuthorsChange,
  handleCategoriesChange,
  handleDescriptionChange,
  handleImageUrlChange,
  handleIsbnChange,
  handleIsOnWishlistChange,
  handleLanguageChange,
  handlePublishedDateChange,
  handlePublisherChange,
  handleThumbnailUrlChange,
  handleTitleChange,
} from './components/bookUtils';

const getFormFields = ({
  title,
  setTitle,
  validTitleClass,
  authors,
  setAuthors,
  publisher,
  setPublisher,
  publishedDate,
  setPublishedDate,
  description,
  setDescription,
  isbn,
  setIsbn,
  categories,
  setCategories,
  thumbnailUrl,
  setThumbnailUrl,
  imageUrl,
  setImageUrl,
  language,
  setLanguage,
  isOnWishlist,
  setIsOnWishlist,
}) => [
  {
    component: FormInput,
    label: 'Title:',
    id: 'title',
    name: 'title',
    type: 'text',
    value: title,
    onChange: handleTitleChange(setTitle),
    validClass: validTitleClass,
  },
  {
    component: FormInput,
    label: 'Author(s):',
    id: 'authors',
    name: 'authors',
    type: 'text',
    value: authors,
    onChange: handleAuthorsChange(setAuthors),
  },
  {
    component: FormInput,
    label: 'Publisher:',
    id: 'publisher',
    name: 'publisher',
    type: 'text',
    value: publisher,
    onChange: handlePublisherChange(setPublisher),
  },
  {
    component: FormInput,
    label: 'Published Date:',
    id: 'publishedDate',
    name: 'publishedDate',
    type: 'date',
    value: publishedDate,
    onChange: handlePublishedDateChange(setPublishedDate),
  },
  {
    component: FormTextarea,
    label: 'Description:',
    id: 'description',
    name: 'description',
    rows: 5,
    value: description,
    onChange: handleDescriptionChange(setDescription),
  },
  {
    component: FormInput,
    label: 'ISBN:',
    id: 'isbn',
    name: 'isbn',
    type: 'text',
    value: isbn,
    onChange: handleIsbnChange(setIsbn),
  },
  {
    component: FormInput,
    label: 'Categories:',
    id: 'categories',
    name: 'categories',
    type: 'text',
    value: categories,
    onChange: handleCategoriesChange(setCategories),
  },
  {
    component: FormInput,
    label: 'ThumbnailUrl:',
    id: 'thumbnailUrl',
    name: 'thumbnailUrl',
    type: 'text',
    value: thumbnailUrl,
    onChange: handleThumbnailUrlChange(setThumbnailUrl),
  },
  {
    component: FormInput,
    label: 'imageUrl:',
    id: 'imageUrl',
    name: 'imageUrl',
    type: 'text',
    value: imageUrl,
    onChange: handleImageUrlChange(setImageUrl),
  },
  {
    component: FormInput,
    label: 'Language:',
    id: 'language',
    name: 'language',
    type: 'text',
    value: language,
    onChange: handleLanguageChange(setLanguage),
  },
  {
    component: FormCheckbox,
    label: 'on wishlist:',
    id: 'on-wishlist',
    name: 'on-wishlist',
    checked: isOnWishlist,
    onChange: handleIsOnWishlistChange(setIsOnWishlist),
  },
];

export default getFormFields;
