import {
  FormCheckbox,
  FormInput,
  FormTextarea,
} from '../../../components/common/FormComponents';
import TitleInputWithSuggestions from '../../../components/common/TitleInputWithSuggestions';
import { getInputClass } from '../../utils/formUtils';

const getBookFormFields = ({ formData, handleFieldChange, handleSelectSuggestion }) => [
  {
    component: TitleInputWithSuggestions,
    label: 'Title:',
    id: 'title',
    name: 'title',
    type: 'text',
    value: formData.title,
    onChange: handleFieldChange,
    onSelectSuggestion: handleSelectSuggestion,
    validClass: getInputClass(formData.validTitle),
  },
  {
    component: FormInput,
    label: 'Author(s):',
    id: 'authors',
    name: 'authors',
    type: 'text',
    value: formData.authors,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'Publisher:',
    id: 'publisher',
    name: 'publisher',
    type: 'text',
    value: formData.publisher,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'Published Date:',
    id: 'publishedDate',
    name: 'publishedDate',
    type: 'date',
    value: formData.publishedDate,
    onChange: handleFieldChange,
  },
  {
    component: FormTextarea,
    label: 'Description:',
    id: 'description',
    name: 'description',
    rows: 5,
    value: formData.description,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'ISBN:',
    id: 'isbn',
    name: 'isbn',
    type: 'text',
    value: formData.isbn,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'Categories:',
    id: 'categories',
    name: 'categories',
    type: 'text',
    value: formData.categories,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'ThumbnailUrl:',
    id: 'thumbnailUrl',
    name: 'thumbnailUrl',
    type: 'text',
    value: formData.thumbnailUrl,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'imageUrl:',
    id: 'imageUrl',
    name: 'imageUrl',
    type: 'text',
    value: formData.imageUrl,
    onChange: handleFieldChange,
  },
  {
    component: FormInput,
    label: 'Language:',
    id: 'language',
    name: 'language',
    type: 'text',
    value: formData.language,
    onChange: handleFieldChange,
  },
  {
    component: FormCheckbox,
    label: 'On Wishlist:',
    id: 'isOnWishlist',
    name: 'isOnWishlist',
    checked: formData.isOnWishlist,
    onChange: handleFieldChange,
  },
];

export default getBookFormFields;
